//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2_Course_Work.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StructureFindFormByYears_checkBox_Checked {
            get {
                return ((bool)(this["StructureFindFormByYears_checkBox_Checked"]));
            }
            set {
                this["StructureFindFormByYears_checkBox_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StructureFindFormByPublisher_checkBox_Checked {
            get {
                return ((bool)(this["StructureFindFormByPublisher_checkBox_Checked"]));
            }
            set {
                this["StructureFindFormByPublisher_checkBox_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal StructureFindFormFromYear_numeric_Value {
            get {
                return ((decimal)(this["StructureFindFormFromYear_numeric_Value"]));
            }
            set {
                this["StructureFindFormFromYear_numeric_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000")]
        public decimal StructureFindFormToYear_numeric_Value {
            get {
                return ((decimal)(this["StructureFindFormToYear_numeric_Value"]));
            }
            set {
                this["StructureFindFormToYear_numeric_Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StructureFindFormPublisher_textBox_Text {
            get {
                return ((string)(this["StructureFindFormPublisher_textBox_Text"]));
            }
            set {
                this["StructureFindFormPublisher_textBox_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StructureFindFormByName_checkBox_Checked {
            get {
                return ((bool)(this["StructureFindFormByName_checkBox_Checked"]));
            }
            set {
                this["StructureFindFormByName_checkBox_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StructureFindFormName_textBox_Text {
            get {
                return ((string)(this["StructureFindFormName_textBox_Text"]));
            }
            set {
                this["StructureFindFormName_textBox_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NameFindForm_Name_textBox_Text {
            get {
                return ((string)(this["NameFindForm_Name_textBox_Text"]));
            }
            set {
                this["NameFindForm_Name_textBox_Text"] = value;
            }
        }
    }
}
